name: thegribs-cookbook
channels:
    - conda-forge
dependencies:
    - jupyterlab
    - mystmd
    - jupyterlab-myst
    - xarray 
    - cartopy
    - matplotlib
    - numpy
    - metpy
    - zarr 
 
