name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst

name: gridradpy
channels: 
    - pip
dependencies:
    - xarray as xr
    - cartopy.crs as ccrs
    - cartopy.feature as cfeature
    - matplotlib.pyplot as plt
    - numpy as np
    - glob 
    - matplotlib.animation import FuncAnimation
    - IPython.display import HTML

