name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst

name: gridradpy
channels: 
    - pip
dependencies:
    - xarray
    - cartopy
    - matplotlib
    - numpy

