name: thegribs-cookbook
channels:
    - conda-forge
dependencies:
    - python>=3.13
    - jupyterlab
    - mystmd
    - jupyterlab-myst
    - xarray
    - cartopy
    - matplotlib
    - numpy
    - pandas
    - metpy
    - zarr
    - sounderpy
    - ipywidgets
    - cfgrib
    - s3fs
    - fsspec
    - herbie-data
    - gcsfs
